version: 0.2

env:
  runtime-versions:
    nodejs: 22

phases:
  install:
    commands:
      - echo "Preparando entorno..."

  pre_build:
    commands:
      - echo "Instalando dependencias del backend..."
      - cd cloudhw-backend && npm install && cd ..

      - echo "Instalando dependencias del frontend..."
      - cd cloudhw-main && npm install && cd ..

  build:
    commands:
      - echo "Construyendo el frontend con Vite..."
      - cd cloudhw-main && npm run build && cd ..

  post_build:
    commands:
      - echo "Empaquetando archivos para despliegue..."

      - mkdir -p deployment_package/backend
      - mkdir -p deployment_package/frontend

      # Backend
      - cp -r cloudhw-backend/* deployment_package/backend/

      # Frontend
      - cp -r cloudhw-main/dist/* deployment_package/frontend/

      # Archivos de despliegue
      - cp appspec.yml deployment_package/
      - cp -r scripts deployment_package/

artifacts:
  files:
    - '**/*'
  base-directory: deployment_package
